celery_project/application/urls.py
from django.urls import path

from . import views

app_name = "application"

urlpatterns = [
    path("email/", views.EmailView.as_view(), name="email_view"),
]

celery_project/celery_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [path("admin/", admin.site.urls), path("", include("application.urls"))]

celery_project/application/models.py
from django.db import models

# Create your models here.

celery_project/application/forms.py
from django import forms

from .tasks import send_email_task


class EmailForm(forms.Form):
    name = forms.CharField(
        label="Name of Person",
        widget=forms.TextInput(attrs={"class": "form-control"}),
        max_length=100,
    )
    email = forms.EmailField(
        label="Email of Person",
        required=True,
        widget=forms.EmailInput(attrs={"class": "form-control"}),
    )
    subject = forms.CharField(
        label="Subject of email",
        max_length=100,
        widget=forms.TextInput(attrs={"class": "form-control"}),
        required=True,
    )
    message = forms.CharField(
        label="Message", widget=forms.Textarea(attrs={"class": "form-control"}), required=True
    )

    def send_email(self):
        # send email using the self.cleaned_data dictionary
        print(self.cleaned_data)
        send_email_task.delay(
            name=self.cleaned_data.get("name"),
            email=self.cleaned_data.get("email"),
            subject=self.cleaned_data.get("subject"),
            message=self.cleaned_data.get("message"),
        )

celery_project/application/views.py
from django.shortcuts import render
from django.views import View

from .forms import EmailForm


class EmailView(View):
    def get(self, request):
        form = EmailForm()
        context = {"form": form}
        return render(request, "application/email.html", context)

    def post(self, request):
        # send email using the self.cleaned_data dictionary
        form = EmailForm(request.POST)
        if form.is_valid():
            form.send_email()
            return render(
                request, "application/email_success.html", {"message": "Email sent successfully"}
            )
        return render(request, "application/email.html", {"form": form})

celery_project/templates/application/email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <title>Document</title>
</head>
<body>
    <div class="container">
        <form action="{% url 'application:email_view' %}" method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Submit" class="btn btn-primary">
        </form>
    </div>
      
</body>
</html>

celery_project/templates/application/email_success.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    />
    <title>Document</title>
  </head>
  <body>
    <div class="container">
      <div class="alert alert-success">
        <strong>Success:</strong>
        {{message}}
      </div>
    </div>
  </body>
</html>